#config-version=FGT60F-7.0.5-FW-build0304-220328:opmode=0:vdom=0
# Configuration fictive et anonyme — fixture de test Calque.
# Adressage RFC1918 inventé ; aucun équipement ni nom réel.
config system global
    set hostname "fw-lab-01"
end
config system interface
    edit "lan"
        set vdom "root"
        set ip 10.10.1.1 255.255.255.0
        set allowaccess ping https ssh
        set type physical
        set role lan
    next
    edit "dmz"
        set vdom "root"
        set ip 10.10.2.1 255.255.255.0
        set allowaccess ping
        set type physical
        set role dmz
    next
    edit "wan"
        set vdom "root"
        set ip 10.200.0.2 255.255.255.252
        set type physical
        set role wan
    next
end
config system zone
    edit "z-dmz"
        set interface "dmz"
    next
end
config router static
    edit 1
        set gateway 10.200.0.1
        set device "wan"
        set distance 10
    next
end
config firewall address
    edit "h-srv-web"
        set subnet 10.10.2.10 255.255.255.255
    next
    edit "r-postes"
        set type iprange
        set start-ip 10.10.1.50
        set end-ip 10.10.1.69
    next
end
config firewall addrgrp
    edit "g-serveurs"
        set member "h-srv-web" "r-postes"
    next
end
config firewall service custom
    edit "TCP-8443"
        set tcp-portrange 8443
    next
    edit "APP-SYNC"
        set tcp-portrange 7000-7010:1024-65535
        set udp-portrange 7000
    next
end
config firewall service group
    edit "g-apps"
        set member "TCP-8443" "APP-SYNC"
    next
end
config firewall policy
    edit 1
        set name "lan-vers-wan"
        set srcintf "lan"
        set dstintf "wan"
        set srcaddr "all"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "ALL"
        set nat enable
    next
    edit 2
        set name "lan-vers-dmz-web"
        set srcintf "lan"
        set dstintf "z-dmz"
        set srcaddr "r-postes"
        set dstaddr "h-srv-web"
        set action accept
        set schedule "always"
        set service "TCP-8443"
    next
    edit 3
        set name "dmz-isolement"
        set srcintf "z-dmz"
        set dstintf "lan"
        set srcaddr "all"
        set dstaddr "all"
        set action deny
        set schedule "always"
        set service "ALL"
    next
    edit 4
        set name "ancienne-regle"
        set srcintf "lan"
        set dstintf "wan"
        set srcaddr "g-serveurs"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "g-apps"
        set status disable
    next
    edit 5
        set name "dmz-vers-wan"
        set srcintf "z-dmz"
        set dstintf "wan"
        set srcaddr "h-srv-web"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "ALL"
    next
end
