!
! Configuration fictive et anonyme - fixture de test Calque.
! Adressage RFC1918 invente ; aucun equipement ni nom reel.
!
version 15.4
service timestamps debug datetime msec
service timestamps log datetime msec
service password-encryption
!
hostname rtr-lab-01
!
boot-start-marker
boot-end-marker
!
enable secret 5 $1$zzzz$condensatEntierementFictif000
!
no aaa new-model
clock timezone CET 1 0
no ip domain-lookup
ip cef
!
object-group network og-serveurs
 description serveurs internes du laboratoire
 host 10.20.2.10
 10.20.3.0 255.255.255.0
!
object-group network og-admin
 group-object og-serveurs
 host 10.20.1.10
!
interface GigabitEthernet0/0
 description LAN utilisateurs
 ip address 10.20.1.1 255.255.255.0
 ip address 10.20.11.1 255.255.255.0 secondary
 ip access-group ACL-ENTREE-LAN in
 duplex full
 speed 1000
 no shutdown
!
interface GigabitEthernet0/0.30
 description invites (sous-interface dot1Q)
 encapsulation dot1Q 30
 ip address 10.20.30.1 255.255.255.0
 ip access-group 130 in
!
interface GigabitEthernet0/1
 description segment serveurs
 ip address 10.20.2.1 255.255.255.0
 ip access-group ACL-SORTIE-SRV out
!
interface GigabitEthernet0/2
 description liaison WAN operateur
 ip address 10.200.1.2 255.255.255.252
!
interface GigabitEthernet0/3
 description lien de secours inutilise
 ip address 10.20.9.1 255.255.255.252
 shutdown
!
ip forward-protocol nd
no ip http server
no ip http secure-server
!
ip route 0.0.0.0 0.0.0.0 10.200.1.1
ip route 10.30.0.0 255.255.0.0 GigabitEthernet0/1 200
!
ip access-list extended ACL-ENTREE-LAN
 permit tcp 10.20.1.0 0.0.0.255 host 10.20.2.10 eq 445
 permit tcp 10.20.1.0 0.0.0.255 object-group og-serveurs range 8000 8010
 permit udp any host 10.20.2.53 eq domain
 permit icmp 10.20.1.0 0.0.0.255 any
 deny ip any any log
!
ip access-list extended ACL-SORTIE-SRV
 permit tcp any host 10.20.2.10 eq 443
 permit tcp any host 10.20.2.10 eq 445
 deny ip any any log
!
access-list 10 remark postes autorises a l'administration
access-list 10 permit 10.20.1.0 0.0.0.255
access-list 10 deny any
access-list 130 permit tcp 10.20.30.0 0.0.0.255 any eq www
access-list 130 permit udp 10.20.30.0 0.0.0.255 any eq domain
access-list 130 deny ip any any
!
logging host 10.20.2.20
snmp-server community lecture-fictive RO
ntp server 10.20.2.30
!
banner motd ^C
 Equipement de laboratoire fictif - acces reserve.
^C
!
line con 0
 exec-timeout 5 0
line vty 0 4
 access-class 10 in
 transport input ssh
!
end
