[package]
name = "calque-parse"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
calque-model = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "fortigate_parse"
harness = false
