[package]
name = "calque-vendors"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
calque-model = { workspace = true }
calque-parse = { workspace = true }
ipnet = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
