[package]
name = "calque-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "calque"
path = "src/main.rs"

[dependencies]
calque-model = { workspace = true }
calque-space = { workspace = true }
calque-policy = { workspace = true }
calque-report = { workspace = true }
calque-engine = { workspace = true }
calque-vendors = { workspace = true }
calque-diff = { workspace = true }
calque-scrub = { workspace = true }
clap = { workspace = true }
ipnet = { workspace = true }
miette = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
assert_cmd = "2"
tempfile = "3"
